env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - airbnb
  - airbnb-typescript
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  - prettier
settings:
  react:
    version: detect
  import/resolver:
    typescript:
      extensions: [".js", ".jsx", ".ts", ".tsx"]
rules:
  semi: ["error", "always"]
  quotes: ["error", "single"]
  max-len: ["error", { "code": 120, "ignoreStrings": true, "ignoreTemplateLiterals": true, "ignoreComments": true }]
  max-classes-per-file: ["error", 5]
  max-nested-callbacks: ["error", 3]
  max-params: ["error", 8]
  max-depth: ["error", 5]
  max-lines-per-function: ["error", 200]
  complexity: ["error", 20]
  arrow-parens: ["error", "always"]
  require-await: ["error"]
  import/extensions: ["error", { "ts": "never" }]
  import/no-unresolved: error
  lines-between-class-members: ["error", "always", { "exceptAfterSingleLine": true }]
  "@typescript-eslint/no-use-before-define": ["error"]
  arrow-body-style: 0
  react/react-in-jsx-scope: 0
  react/jsx-props-no-spreading: 0
  react/require-default-props: ["error", { "functions": "defaultArguments" }]
  import/prefer-default-export: 0
  no-trailing-spaces: ["error", { "skipBlankLines": true, "ignoreComments": true }]
  camelcase: error
  spaced-comment: error
  no-duplicate-imports: error
  react-hooks/exhaustive-deps: 0
